### ISSUE TITLE
[FEAT] 사용자 API 구현

### ISSUE THREAD

**Issue by sonaanweb** [sonaanweb/plan-budget#1]
### 사용자 회원가입(API)
- `계정` , `패스워드` 입력하여 회원가입

### 사용자 로그인(API)
- 로그인 시  `JWT`  발급
- 이후 모든 API 요청 Header 에 `JWT` 가 항시 포함되며, `JWT` 유효성 검증

## 📒 To-do

- [x] Member 엔티티 설계
- [ ] 회원가입 API 구현
- [ ] 로그인 API 구현
